---
- name: oh git
  hosts: all
  become_user: root

  tasks:
  - name: add lines
    lineinfile:
        path: /home/ubuntu/hari
        line: 'your line to add'
        line: "can we add this too"
        create: yes

